services:

  # Postgres
  db-talk-postgres:
    image: postgres:16
    container_name: db-talk-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - db_talk_postgres_data:/var/lib/postgresql/data
    networks:
      - db-talk-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis
  db-talk-redis:
    image: redis:7
    container_name: db-talk-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - db_talk_redis_data:/data
    networks:
      - db-talk-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend
  db-talk-backend:
    image: kamal2502/db-talk-backend:fd51412
    container_name: db-talk-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      PORT: ${PORT}
      ENV: ${ENV}
      DB_TALK_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-talk-postgres:5432/${POSTGRES_DB}
      REDIS_URL: ${REDIS_URL}
      AI_API_KEY: ${AI_API_KEY}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_ENCRYPTION_SECRET: ${REDIS_ENCRYPTION_SECRET}
    depends_on:
      db-talk-postgres:
        condition: service_healthy
      db-talk-redis:
        condition: service_healthy
    networks:
      - db-talk-network
    volumes:
      - ./backend/logs:/app/logs

  # Frontend
  db-talk-frontend:
    image: kamal2502/db-talk-frontend:fd51412
    container_name: db-talk-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    depends_on:
      - db-talk-backend
    networks:
      - db-talk-network

volumes:
  db_talk_postgres_data:
    driver: local
  db_talk_redis_data:
    driver: local

networks:
  db-talk-network:
    driver: bridge
