services:
  DB-talk-postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: db_talk_user
      POSTGRES_PASSWORD: db_talk_password
      POSTGRES_DB: db_talk_db
    ports:
      - "5432:5432"
    volumes:
      - db_talk_postgres_data:/var/lib/postgresql/data

  DB-talk-redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - db_talk_redis_data:/data
    command: redis-server --appendonly yes


volumes:
  db_talk_postgres_data:
  db_talk_redis_data:
