name: Build and Push DB-Talk

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths-ignore:
      - docker-compose.yml

  workflow_dispatch:

env:
  REGISTRY: kamal2502

jobs:

  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}

    steps:
      - uses: actions/checkout@v5

      - name: Detect changed files
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

  frontend:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'

    steps:
      - uses: actions/checkout@v5

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - name: Build & push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: kamal2502/db-talk-frontend:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  backend:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'

    steps:
      - uses: actions/checkout@v5

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - name: Build & push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: kamal2502/db-talk-backend:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-compose:
    runs-on: ubuntu-latest
    needs: [detect-changes]

    # run if at least one changed
    if: |
      needs.detect-changes.outputs.frontend == 'true' ||
      needs.detect-changes.outputs.backend == 'true'

    steps:
      - uses: actions/checkout@v5

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Update docker-compose.yml
        run: |
          if [ "${{ needs.detect-changes.outputs.frontend }}" = "true" ]; then
            sed -i "s|kamal2502/db-talk-frontend:.*|kamal2502/db-talk-frontend:${IMAGE_TAG}|g" docker-compose.yml
          fi

          if [ "${{ needs.detect-changes.outputs.backend }}" = "true" ]; then
            sed -i "s|kamal2502/db-talk-backend:.*|kamal2502/db-talk-backend:${IMAGE_TAG}|g" docker-compose.yml
          fi

      - name: Commit compose update
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docker-compose.yml
          git commit -m "SYSTEM: update images ${IMAGE_TAG}" || echo "No changes"
          git push
